### ISSUE TITLE
Provider seems buggy sometime, it is unresponsive for a couple of seconds

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/provider#173] opened 2021-07-01 15:04 UTC
Sometimes we are getting this error 'Finding the service endpoints failed' when using Ocean.js directly with barge? Seems to happen at random without changing any code

```
Finding the service endpoints failed: AbortError: The user aborted a request.
    at abort (/home/jamie/Desktop/workshop/quickstart1/node_modules/node-fetch/lib/index.js:1418:16)
    at EventEmitter.abortAndFinalize (/home/jamie/Desktop/workshop/quickstart1/node_modules/node-fetch/lib/index.js:1433:4)
    at EventEmitter.emit (events.js:315:20)
    at AbortSignal.dispatchEvent (/home/jamie/Desktop/workshop/quickstart1/node_modules/node-abort-controller/index.js:28:23)
    at AbortController.abort (/home/jamie/Desktop/workshop/quickstart1/node_modules/node-abort-controller/index.js:40:17)
    at Timeout._onTimeout (/home/jamie/Desktop/workshop/quickstart1/node_modules/@oceanprotocol/lib/dist/node/lib.js:1:26814)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  type: 'aborted'
}
```
```
const run = async () => {
    const blob = `http://localhost:8030/api/v1/services/consume`;
    const ocean = await Ocean.getInstance(config);
    const accounts = await ocean.accounts.list();
    const alice = accounts[0];
    const bob = accounts[1];
    console.log('Alice account address:', alice.id)
    console.log('Bob account address:', bob.id)
    const datatoken = new DataTokens(
      contracts.DTFactory,
      factoryABI,
      datatokensABI,
      new Web3(urls.networkUrl)
    );
    const tokenAddress = await datatoken.create(
       blob, 
       alice.getId(),
       '10000000000',
       'AliceDT',
       'DTA');
    console.log(`Deployed datatoken address: ${tokenAddress}`);
    };
run();
```

**Comment by alexcos20** [comment] 2021-07-01 15:06
see https://github.com/oceanprotocol/ocean.js/issues/859 also

**Comment by alexcos20** [comment] 2021-07-01 15:43
so, the failing code in ocean.js is here: https://github.com/oceanprotocol/ocean.js/blob/666da8156fda8a3201b5b4cd600105017f65b275/src/provider/Provider.ts#L62

meaning that we are trying to get the endpoint of the provider, by calling the root endpoint.  and that is failing

**Comment by jamiehewitt15** [comment] 2021-07-01 16:15
The other error that I see quite regularly is:
```
Error requesting [GET] http://localhost:5000/api/v1/aquarius/assets/ddo/did:op:2fCB77799F39B61E9eD898819D3D71f983BE4E21
Response message: 
did:op:2fCB77799F39B61E9eD898819D3D71f983BE4E21 asset DID is not in OceanDB
Error fetching querying metadata:  Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      [Symbol(kCapture)]: false,
      [Symbol(kTransformState)]: [Object]
    },
    disturbed: true,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'http://localhost:5000/api/v1/aquarius/assets/ddo/did:op:2fCB77799F39B61E9eD898819D3D71f983BE4E21',
    status: 404,
    statusText: 'NOT FOUND',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}
```

**Comment by jamiehewitt15** [comment] 2021-07-01 16:17
If the bug is due to a recent upgrade to provider I could use a previous version that works reliably for the demo next week.

**Comment by DMats** [comment] 2021-07-01 21:11
@alexcos20 I'm not sure how to debug the issue with getting exposed provider endpoints. The provider function that is bound to the root endpoint seems really straightforward. https://github.com/oceanprotocol/provider/blob/main/ocean_provider/run.py#L61

@jamiehewitt15 I have also witnessed the "asset DID is not in OceanDB" issue - while testing ocean.py on Rinkeby. https://github.com/oceanprotocol/ocean.py/pull/309#issuecomment-866047915 At the time, stable-aqua on Rinkeby still had the issue where it stopped indexing after a while. I haven't retried the test yet.

**Comment by jamiehewitt15** [comment] 2021-07-05 06:35
@DMats Thanks, I was using the main branch so I will have a go with the `feature/stable-aqua` branch

**Comment by jamiehewitt15** [comment] 2021-07-05 09:08
I tried using the stable aqua branch and I'm still getting the "Finding the service endpoints failed" error. It still seems quite random, the error doesn't happen in the same point each time and sometimes it won't happen. 

```
Finding the service endpoints failed: AbortError: The user aborted a request.
    at abort (/home/jamie/Desktop/workshop/quickstart1/node_modules/node-fetch/lib/index.js:1418:16)
    at EventEmitter.abortAndFinalize (/home/jamie/Desktop/workshop/quickstart1/node_modules/node-fetch/lib/index.js:1433:4)
    at EventEmitter.emit (events.js:315:20)
    at AbortSignal.dispatchEvent (/home/jamie/Desktop/workshop/quickstart1/node_modules/node-abort-controller/index.js:28:23)
    at AbortController.abort (/home/jamie/Desktop/workshop/quickstart1/node_modules/node-abort-controller/index.js:40:17)
    at Timeout._onTimeout (/home/jamie/Desktop/workshop/quickstart1/node_modules/@oceanprotocol/lib/dist/node/lib.js:1:26814)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  type: 'aborted'
}
AbortError: The user aborted a request.
    at abort (/home/jamie/Desktop/workshop/quickstart1/node_modules/node-fetch/lib/index.js:1418:16)
    at EventEmitter.abortAndFinalize (/home/jamie/Desktop/workshop/quickstart1/node_modules/node-fetch/lib/index.js:1433:4)
    at EventEmitter.emit (events.js:315:20)
    at AbortSignal.dispatchEvent (/home/jamie/Desktop/workshop/quickstart1/node_modules/node-abort-controller/index.js:28:23)
    at AbortController.abort (/home/jamie/Desktop/workshop/quickstart1/node_modules/node-abort-controller/index.js:40:17)
    at Timeout._onTimeout (/home/jamie/Desktop/workshop/quickstart1/node_modules/@oceanprotocol/lib/dist/node/lib.js:1:26814)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  type: 'aborted'
}
ERROR: Failed to order a service : HTTP request failed
(node:31889) UnhandledPromiseRejectionWarning: Error: Failed to order a service: HTTP request failed
    at fs.order (/home/jamie/Desktop/workshop/quickstart1/node_modules/@oceanprotocol/lib/dist/node/lib.js:1:226641)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async run (/home/jamie/Desktop/workshop/quickstart1/index.js:91:25)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31889) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31889) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jamiehewitt15** [comment] 2021-07-05 16:54
@DMats these are the provider logs I'm getting when running it locally with barge:

```
provider_1         | 2021-07-05 15:40:43,435 - ocean_provider.routes.consume - INFO - nonce for user 0xe2DD09d719Da89e5a3D0F2549c7E24566e947260 is 135
provider_1         | 2021-07-05 15:40:43,440 - ocean_provider.routes.consume - INFO - encrypted urls 0x04dcba59507bc3aae6aa0aef09e77a63008cc693beb490d360465658e63d77bba99695fea6554f493e8b3021744ae81d497da067c013a88827d08347c21b1ac9e6f7f10015802903e4813eec2eb8ec25a58c40ae05a3e83e2b45714000efcce26b6cb0dafb73adac5559421d465c1092737cf8a783d645393a6208cef61273f9a248837624ab9e0e674293989e689cc09b3b12066b367ca60dc182de44f6df5be20e1fb3ae9b8b10fc8aa3d55008df8a335896b8f6f5c429c01ed2d8bc348ab72f208e870431bef97636794e0f, publisher 0xe2DD09d719Da89e5a3D0F2549c7E24566e947260, documentId did:op:a1185CC3aeA8b21CA343741573B65CD7b1b77D9E


provider_1         | 2021-07-05 15:41:38,840 - ocean_provider.util - ERROR - Error getting CtD address: HTTPSConnectionPool(host='c2d-dev.operator.oceanprotocol.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0009946310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
provider_1         | 2021-07-05 15:41:43,844 - ocean_provider.util - ERROR - Error getting CtD address: HTTPSConnectionPool(host='c2d-dev.operator.oceanprotocol.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0009996400>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

```

**Comment by DMats** [comment] 2021-07-06 03:55
Hey, @jamiehewitt15 I ran through the beginners quickstart and the marketplace quickstart using barge on the `main` branch, `stable-aqua` branch, and the `latest` branch but have been unable to replicate the issues you're seeing with the provider.  I also tried the snippet posted in the description of this issue but got the same results.

Can you share with me your full test procedure including setup and the node script?

**Comment by alexcos20** [comment] 2021-07-06 05:11
@jamiehewitt15 - if you don't plan to use C2D, you could remove https://github.com/oceanprotocol/barge/blob/main/compose-files/provider.yml#L22

**Comment by jamiehewitt15** [comment] 2021-07-06 06:23
@alexcos20 that's a good idea, I'll give it a go. I'm not using compute to data. 

@DMats Thanks for looking into this. You can see all of the code here: https://github.com/jamiehewitt15/OceanWorkshop I added a readme that has the steps I am using to to run the project. The error seems to be quite random sometimes it works perfectly and then other times it gets the "Finding the service endpoints failed" error.

**Comment by jamiehewitt15** [comment] 2021-07-06 11:45
@alexcos20 I tried your suggestion and it seems to be working now

**Comment by DMats** [comment] 2021-07-08 20:38
@jamiehewitt15 I attempted cloning and running https://github.com/jamiehewitt15/OceanWorkshop but received the following error while creating a DataToken. Thus, I was unable to reproduce the intermittent errors "Finding the service endpoints failed"

<details>
<summary>OceanWorkshop console log</summary>
<p>

```console
david@david-Inspiron-5502:~/projects/OceanWorkshop$ node index
Alice account address: 0xe2DD09d719Da89e5a3D0F2549c7E24566e947260
Bob account address: 0xBE5449a6A97aD46c8558A3356267Ee5D2731ab5e
(node:16214) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'error' of undefined
    at As.create (/home/david/projects/OceanWorkshop/node_modules/@oceanprotocol/lib/dist/node/lib.js:1:239978)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async run (/home/david/projects/OceanWorkshop/index.js:28:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16214) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

</p>
</details>

I'm going to change gears. I'll look at the ocean.js Github Actions and CI Workflows to get a better sense of the intermittent provider failures that are blocking the front-end team.

**Comment by jamiehewitt15** [comment] 2021-07-09 10:48
There is an example of the  "Finding the service endpoints failed" error on the ocean.js tests here: https://github.com/oceanprotocol/ocean.js/pull/895/checks?check_run_id=3020105627#step:11:2211 

I can also find more examples if it helps

**Comment by jamiehewitt15** [comment] 2021-07-09 13:05
Same error also happened here: https://github.com/oceanprotocol/ocean.js/runs/3029041949?check_suite_focus=true#step:11:161

**Comment by DMats** [comment] 2021-07-13 12:18
We discussed this issue at the backend grooming session. 

I've been unable to diagnose why this error is occurring so we decided I should start adding logging to the Provider component.

**Comment by alexcos20** [comment] 2021-08-23 14:33
This is why provider fails:

2021-08-23T14:06:07.4711901Z 2021-08-23 13:56:52,513 - ocean_provider.myapp - ERROR - Exception on /api/v1/services/compute [POST]
2021-08-23T14:06:07.4712634Z Traceback (most recent call last):
2021-08-23T14:06:07.4713751Z   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
2021-08-23T14:06:07.4714494Z     httplib_response = self._make_request(
2021-08-23T14:06:07.4715474Z   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
2021-08-23T14:06:07.4716333Z     six.raise_from(e, None)
2021-08-23T14:06:07.4716801Z   File "<string>", line 3, in raise_from
2021-08-23T14:06:07.4717774Z   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
2021-08-23T14:06:07.4718720Z     httplib_response = conn.getresponse()
2021-08-23T14:06:07.4719938Z   File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
2021-08-23T14:06:07.4720508Z     response.begin()
2021-08-23T14:06:07.4721330Z   File "/usr/lib/python3.8/http/client.py", line 303, in begin
2021-08-23T14:06:07.4722319Z     version, status, reason = self._read_status()
2021-08-23T14:06:07.4723128Z   File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
2021-08-23T14:06:07.4723984Z     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2021-08-23T14:06:07.4724796Z   File "/usr/lib/python3.8/socket.py", line 669, in readinto
2021-08-23T14:06:07.4725533Z     return self._sock.recv_into(b)
2021-08-23T14:06:07.4726058Z   File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
2021-08-23T14:06:07.4726976Z     return self.read(nbytes, buffer)
2021-08-23T14:06:07.4727543Z   File "/usr/lib/python3.8/ssl.py", line 1099, in read
2021-08-23T14:06:07.4728282Z     return self._sslobj.read(len, buffer)
2021-08-23T14:06:07.4729280Z ConnectionResetError: [Errno 104] Connection reset by peer
2021-08-23T14:06:07.4729729Z 
2021-08-23T14:06:07.4730865Z During handling of the above exception, another exception occurred:
2021-08-23T14:06:07.4731450Z 
2021-08-23T14:06:07.4731875Z Traceback (most recent call last):
2021-08-23T14:06:07.4733156Z   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
2021-08-23T14:06:07.4733808Z     resp = conn.urlopen(
2021-08-23T14:06:07.4735086Z   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
2021-08-23T14:06:07.4735860Z     retries = retries.increment(
2021-08-23T14:06:07.4736935Z   File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 532, in increment
2021-08-23T14:06:07.4737712Z     raise six.reraise(type(error), error, _stacktrace)
2021-08-23T14:06:07.4738946Z   File "/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py", line 769, in reraise
2021-08-23T14:06:07.4739638Z     raise value.with_traceback(tb)
2021-08-23T14:06:07.4740848Z   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
2021-08-23T14:06:07.4741619Z     httplib_response = self._make_request(
2021-08-23T14:06:07.4742616Z   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
2021-08-23T14:06:07.4743329Z     six.raise_from(e, None)
2021-08-23T14:06:07.4743797Z   File "<string>", line 3, in raise_from
2021-08-23T14:06:07.4745153Z   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
2021-08-23T14:06:07.4746170Z     httplib_response = conn.getresponse()
2021-08-23T14:06:07.4746867Z   File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
2021-08-23T14:06:07.4747575Z     response.begin()
2021-08-23T14:06:07.4748127Z   File "/usr/lib/python3.8/http/client.py", line 303, in begin
2021-08-23T14:06:07.4748715Z     version, status, reason = self._read_status()
2021-08-23T14:06:07.4749320Z   File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
2021-08-23T14:06:07.4750152Z     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2021-08-23T14:06:07.4750939Z   File "/usr/lib/python3.8/socket.py", line 669, in readinto
2021-08-23T14:06:07.4751461Z     return self._sock.recv_into(b)
2021-08-23T14:06:07.4751994Z   File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
2021-08-23T14:06:07.4752579Z     return self.read(nbytes, buffer)
2021-08-23T14:06:07.4753327Z   File "/usr/lib/python3.8/ssl.py", line 1099, in read
2021-08-23T14:06:07.4755668Z     return self._sslobj.read(len, buffer)
2021-08-23T14:06:07.4757486Z urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2021-08-23T14:06:07.4759504Z 
2021-08-23T14:06:07.4761095Z During handling of the above exception, another exception occurred:
2021-08-23T14:06:07.4761971Z 
2021-08-23T14:06:07.4762639Z Traceback (most recent call last):
2021-08-23T14:06:07.4764475Z   File "/ocean-provider/ocean_provider/routes/compute.py", line 335, in computeStart
2021-08-23T14:06:07.4765717Z     response = requests_session.post(
2021-08-23T14:06:07.4767516Z   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 590, in post
2021-08-23T14:06:07.4769405Z     return self.request('POST', url, data=data, json=json, **kwargs)
2021-08-23T14:06:07.4770903Z   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
2021-08-23T14:06:07.4771839Z     resp = self.send(prep, **send_kwargs)
2021-08-23T14:06:07.4773069Z   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 655, in send
2021-08-23T14:06:07.4773953Z     r = adapter.send(request, **kwargs)
2021-08-23T14:06:07.4775041Z   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 498, in send
2021-08-23T14:06:07.4775804Z     raise ConnectionError(err, request=request)
2021-08-23T14:06:07.4777227Z requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2021-08-23T14:06:07.4779023Z 
2021-08-23T14:06:07.4779665Z During handling of the above exception, another exception occurred:
2021-08-23T14:06:07.4780119Z 
2021-08-23T14:06:07.4780568Z Traceback (most recent call last):
2021-08-23T14:06:07.4781625Z   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
2021-08-23T14:06:07.4782313Z     response = self.full_dispatch_request()
2021-08-23T14:06:07.4783285Z   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
2021-08-23T14:06:07.4784090Z     rv = self.handle_user_exception(e)
2021-08-23T14:06:07.4785071Z   File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
2021-08-23T14:06:07.4786062Z     return cors_after_request(app.make_response(f(*args, **kwargs)))
2021-08-23T14:06:07.4787229Z   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
2021-08-23T14:06:07.4787926Z     reraise(exc_type, exc_value, tb)
2021-08-23T14:06:07.4789160Z   File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
2021-08-23T14:06:07.4790078Z     raise value
2021-08-23T14:06:07.4790941Z   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
2021-08-23T14:06:07.4791687Z     rv = self.dispatch_request()
2021-08-23T14:06:07.4792723Z   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
2021-08-23T14:06:07.4793503Z     return self.view_functions[rule.endpoint](**req.view_args)
2021-08-23T14:06:07.4794496Z   File "/usr/local/lib/python3.8/dist-packages/flask_sieve/validator.py", line 81, in wrapper
2021-08-23T14:06:07.4795216Z     return fn(*args, **kwargs)
2021-08-23T14:06:07.4796070Z   File "/ocean-provider/ocean_provider/routes/compute.py", line 347, in computeStart
2021-08-23T14:06:07.4797162Z     return service_unavailable(e, data, logger)
2021-08-23T14:06:07.4798258Z   File "/ocean-provider/ocean_provider/utils/util.py", line 333, in service_unavailable
2021-08-23T14:06:07.4798959Z     text_items.append(key + "=" + value)
2021-08-23T14:06:07.4799727Z TypeError: can only concatenate str (not "dict") to str




fixed in https://github.com/oceanprotocol/provider/pull/201/commits/21d085c3354ea07acf4cf3bd0835b505cd86c876

**Closed** 2021-08-31 12:58 UTC
Labels: Type: Bug, Priority: High
