### ISSUE TITLE
During compute start, files checksum for algorithm are not checking against file content

### ISSUE THREAD

**Issue by soonhuat** [oceanprotocol/provider#494] opened 2022-06-23 07:24 UTC
**Description**
Algorithm files checksum checking performed during compute start are checking against hash of encrypted files (asset.files)
https://github.com/oceanprotocol/provider/blob/408a9032b30d3606a6b991f3982b7d17ded7cd47/ocean_provider/validation/algo.py#L415

**Describe the solution**
Algorithm files checksum should check based on the contents, perhaps similar implementation as 
https://github.com/oceanprotocol/provider/blob/408a9032b30d3606a6b991f3982b7d17ded7cd47/ocean_provider/routes/consume.py#L111
with_checksum = true

**Comment by alexcos20** [comment] 2022-06-23 07:31
duplicate of https://github.com/oceanprotocol/multi-repo-issue/issues/153

**Closed by alexcos20** 2022-06-23 07:31 UTC
Labels: Type: Bug
