### ISSUE TITLE
Azure dataset, local provider, osmosis removal

### ISSUE THREAD

**Issue by aghatpande** [oceanprotocol/provider#377] opened 2022-02-17 21:01 UTC
Hi, I want to publish a data asset stored as a blob in Azure on the rinkeby testnet. I plan to run provider locally with all the Azure credentials needed as instructed in this tutorial (https://docs.oceanprotocol.com/tutorials/azure-for-provider/). I was wondering if you expect any issues to arise given that "osmosis" was removed recently? Thank you for your attention and your work.

**Comment by DMats** [comment] 2022-02-22 23:04
Thanks for the question, @aghatpande. Support for Azure blobs that require credentials was removed. We still support Azure blobs that are public and can be downloaded via a URL.

As a side note, the tutorial you referenced is was never updated for Ocean v3.  We've scheduled to update it for v4: https://github.com/oceanprotocol/docs/issues/900

**Comment by aghatpande** [comment] 2022-02-23 23:36
@DMats thanks for the help. I am still unable to publish my azure blob. Its accessible to anonymous public (storage a/c , container and blob permissions set). I published the same data from google drive, see this: did:op:EB1D3BA7dd6B0a0C9793017A12D096f1406D813C. I'm using ocean.py. I think the problem may be that the provider on rinkeby is not updated to the one recently modified? Here's the config.ini I am using:
[eth-network]
network = https://rinkeby.infura.io/v3/d163c48816434b0bbb3ac3925d6c6c80
block_confirmations = 0

[resources]
metadata_cache_uri = https://aquarius.oceanprotocol.com
provider.url = https://provider.rinkeby.oceanprotocol.com
provider.address = 0x00bd138abd70e2f00903268f3db08f2d25677c9e

downloads.path = consume-downloads

Please advise, thanks again

**Comment by jamiehewitt15** [comment] 2022-03-11 12:03
@aghatpande your issue with publishing an Azure asset appears to be a duplicate of https://github.com/oceanprotocol/provider/issues/356 which was fixed today

**Closed by jamiehewitt15** 2022-03-11 12:03 UTC
